//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serg_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public int BusinessID { get; set; }
        public Nullable<int> CatID { get; set; }
        public string CatName { get; set; }
        public string BusinessName { get; set; }
        public string Location { get; set; }
        public string BusinessDesc { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FaceBook { get; set; }
        public string WebSite { get; set; }
        public string BusinessImage { get; set; }
        public string Likes { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
